version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-bravabook}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - bravabook-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bravabook-api
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/${MONGO_DATABASE:-bravabook}?authSource=admin
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - bravabook-network

networks:
  bravabook-network:
    driver: bridge

volumes:
  mongodb_data:
    name: mongodb_data
